### ISSUE TITLE
Login Controllers

### ISSUE THREAD

**Issue by mwang25277** [madisonwheeler/TenantTracker#6]
I can take the inputted username and password, find the corresponding User in the table, and I'm pretty sure I am returning True in LoginService, however the LoginController for both landlords and tenants still reads it as an error?

**Comment by mwang25277** [comment]
implemented a bandaid fix which uses rootScope instead of a service

**Comment by danwestover** [comment]
rootScope was replaced with ngStorage sessionStorage.
